#!/usr/bin/env python3
"""
Make AI application traffic appear in Application Discovery.

    python3 generate_ai_traffic.py                 one round, report what resolved
    python3 generate_ai_traffic.py --rounds 6      six rounds, spaced out
    python3 generate_ai_traffic.py --seed          setup mode: many rounds, quiet
    python3 generate_ai_traffic.py --check         report only, generate nothing

Application Discovery classifies applications from the DNS queries the DFP
observes. No queries means an empty report, and an empty report means the
participant has nothing to classify and the lab has no first act.

## Why this runs at setup and not only in the challenge

The queries have to be seen, aggregated and classified by Threat Defense before
an application shows up under "Needs Review". That pipeline is not instant and
Infoblox does not document how long it takes. If the first traffic were
generated by the participant at the start of challenge 2, they could sit
looking at an empty report for an unknown number of minutes, which reads as a
broken lab.

So setup seeds the report, and the challenge asks the participant to browse the
tools themselves as well. By the time they open the report there is already
data in it, and their own browsing adds to it. Both are true: they really did
generate the traffic, and they are not waiting on a pipeline nobody can put a
number on.

## Why the queries come from the desktop

Application Discovery attributes applications to the *device* that asked. The
Instruqt shell container is not behind the DFP and is not a device in this
tenant, so lookups from there would not appear at all. Every query here is
executed on the Windows desktop over WinRM, which is the same client the
participant then uses in the browser.

Environment: DESKTOP_IP, TF_VAR_windows_admin_password, DFP_PRIVATE_IP.
"""

import argparse
import sys
import time

import domains as D
from csp_api import get_logger
from desktop_dns import DesktopUnreachable, explain_failure, probe_desktop

log = get_logger("generate_ai_traffic")


def one_round(domains, quiet=False):
    """
    Resolve every domain once from the desktop.

    Returns the probe dict from desktop_dns.probe_desktop.
    """
    probe = probe_desktop(domains)
    if quiet:
        return probe

    for domain, result in probe["results"].items():
        entry = D.entry_for_domain(domain)
        app = entry["app"] if entry else "-"
        detail = (", ".join(result["addresses"][:2]) if result["resolved"]
                  else result["status"])
        log.info("  %-30s %-18s %s", domain, app, detail)

    return probe


def generate(rounds=1, interval=20, quiet=False, include_extra=True):
    """
    Drive several rounds of AI lookups from the desktop.

    Repetition is not superstition: a single query for a name can be served
    from the desktop's own cache or missed by aggregation, and Application
    Discovery is more reliable about an application it has seen a few times.
    The DNS client cache is cleared at the start of every round by the
    PowerShell in desktop_dns.
    """
    targets = D.all_domains(include_extra=include_extra) + [D.CONTROL_DOMAIN]
    log.info("Generating traffic for %d domain(s) across %d round(s)",
             len(targets), rounds)

    resolved_any = set()
    last = None

    for index in range(1, rounds + 1):
        if rounds > 1:
            log.info("--- round %d/%d ---", index, rounds)
        try:
            last = one_round(targets, quiet=quiet)
        except DesktopUnreachable as exc:
            log.error("Desktop unreachable: %s", exc)
            return None, resolved_any

        for domain, result in last["results"].items():
            if result["resolved"]:
                resolved_any.add(domain)

        if index < rounds:
            time.sleep(interval)

    return last, resolved_any


def summarise(probe, resolved_any):
    """Print what the traffic run achieved, and what it implies."""
    if not probe:
        return 1

    apps_seen = set()
    for domain in resolved_any:
        entry = D.entry_for_domain(domain)
        if entry:
            apps_seen.add(entry["app"])

    control = probe["results"].get(D.CONTROL_DOMAIN, {})

    print()
    print("=" * 70)
    print("  Traffic generated")
    print("=" * 70)
    print(f"  Resolver             {probe['server']}")
    print(f"  Desktop DNS set to   {', '.join(probe['configured_dns']) or 'none'}")
    print(f"  Domains resolved     {len(resolved_any)}")
    print(f"  AI applications hit  {len(apps_seen)}/{len(D.app_names())}")
    for name in D.app_names():
        mark = "yes" if name in apps_seen else "NO"
        print(f"    {name:<24} {mark}")
    print(f"  Control domain       "
          f"{'resolves' if control.get('resolved') else 'DOES NOT RESOLVE'}"
          f"  ({D.CONTROL_DOMAIN})")
    print("=" * 70)

    reason = explain_failure(probe)
    if reason:
        print(f"\n  ! {reason}\n")
        return 1

    missing = [n for n in D.app_names() if n not in apps_seen]
    if missing:
        # Not fatal. A blocked application will not resolve, and after the
        # policy is applied that is the desired state, so this is information
        # rather than an error.
        print(f"\n  Note: no successful lookup for {', '.join(missing)}.")
        print("  Before the policy exists that suggests a resolution problem.")
        print("  After the policy exists it is exactly what a block looks like.\n")
    else:
        print("\n  All AI applications were resolved. Application Discovery "
              "should populate shortly.\n")
    return 0


def main():
    parser = argparse.ArgumentParser(
        description="Generate AI application DNS traffic from the Windows desktop.")
    parser.add_argument("--rounds", type=int, default=1,
                        help="How many times to walk the domain list")
    parser.add_argument("--interval", type=int, default=20,
                        help="Seconds between rounds")
    parser.add_argument("--seed", action="store_true",
                        help="Setup mode: 4 rounds, 30s apart, quiet per-domain output")
    parser.add_argument("--check", action="store_true",
                        help="Resolve once and report, without the summary framing")
    parser.add_argument("--primary-only", action="store_true",
                        help="Only the five headline domains, not their API domains")
    args = parser.parse_args()

    rounds = args.rounds
    interval = args.interval
    quiet = False

    if args.seed:
        rounds, interval, quiet = 4, 30, True

    if args.check:
        try:
            probe = one_round(D.primary_domains() + [D.CONTROL_DOMAIN])
        except DesktopUnreachable as exc:
            log.error("%s", exc)
            return 1
        reason = explain_failure(probe)
        if reason:
            log.error("%s", reason)
            return 1
        return 0

    probe, resolved = generate(rounds=rounds, interval=interval, quiet=quiet,
                              include_extra=not args.primary_only)
    return summarise(probe, resolved)


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
    except Exception as exc:  # noqa: BLE001 — top-level guard
        log.error("%s", exc)
        sys.exit(1)
